### ISSUE TITLE
AlexNet/ ZFNet 코드 리뷰

### ISSUE THREAD

**Issue by deblee2** [yskim0/pytorch-cifar10#2]
## alexnet.py
코드가 깔끔하게 작성된 것 같습니다. Alexnet에서 중요한 ReLU, pooling, dropout 등이 코드에 잘 포함되어 있네요. 논문에는 커널을 96->256->384->384->256으로 설정하였는데 코드에서는 64->192->384->256->256으로 설정하신 이유가 궁금해요! mnist와 cifar-10의 차이인지 아니면 성능을 더 좋게 하기 위해서 하신건지 알고싶어요.

기본적인 틀은 다 갖추어져 있으니 성능 평가 지표를 더 향상시킬 수 있게 추가적으로 하이퍼 파라미터를 바꿔보거나 conv layer를 더 추가하는 작업을 해보셔도 좋을 것 같습니다.

## ZFNet.py
ZFNet 코드를 보니까 텐서플로보다 파이토치가 훨씬 더 심플하게 표현하기 좋다는 생각이 드네요! 저도 다음에는 파이토치에 도전해봐야 겠습니다ㅎㅎ 군더더기 없이 잘 작성된 것 같습니다. 한 가지 제안하고 싶은건 전체적으로 주석을 달아서 각각의 어떤 역할을 하고 있는지 설명을 덧붙이면 더 좋을 것 같아요.

**Comment by yskim0** [comment]
우선 코드리뷰 감사합니다 😄 

## alexnet.py
> 코드가 깔끔하게 작성된 것 같습니다. Alexnet에서 중요한 ReLU, pooling, dropout 등이 코드에 잘 포함되어 있네요. 논문에는 커널을 96->256->384->384->256으로 설정하였는데 코드에서는 64->192->384->256->256으로 설정하신 이유가 궁금해요! mnist와 cifar-10의 차이인지 아니면 성능을 더 좋게 하기 위해서 하신건지 알고싶어요.
기본적인 틀은 다 갖추어져 있으니 성능 평가 지표를 더 향상시킬 수 있게 추가적으로 하이퍼 파라미터를 바꿔보거나 conv layer를 더 추가하는 작업을 해보셔도 좋을 것 같습니다.

음 그러게요... 진짜 왜 64부터 했을까요...  사실 alexnet은 논문 안읽고 그냥 아키텍쳐랑 reference들 보고 해서,,, 틀린 부분이 있군요...
제가 참고한 코드는 파이토치 공식? 레포지터리에서 쓴 코드인데 흠... [참고 코드](https://github.com/pytorch/vision/blob/master/torchvision/models/alexnet.py) 
-----
**지금 찾아봤는데 이유가 있네요!**
> I looked it further, and our current implementation comes from the torch re-implementation, which is based on the single GPU implementation from Alex which uses 256 filters, while the 2GPU implementation from Krizhevsky uses 384 filters.
So it seems that this bug comes from a long time already.
[참고](https://github.com/pytorch/vision/pull/463#issuecomment-379214941)

틀린 부분 지적해주셔서 고맙습니다! 덕분에 저도 더 알아가요 ㅋㅋ 👍 


## ZFNet.py

오 레이어 설명말씀하시는 건가요? @deblee2 코드에는 모델 설명이 잘 되어있어서 보기 좋더군요 ㅎㅎ
감사합니다!

**Comment by yskim0** [comment]
우선 close 하겠습니다. 추가 질문있으시면 comment 달아주세요!
